apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: '*/1 * * * *'
  startingDeadlineSeconds: 22
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      name: hello
    spec:
      template:
        metadata:
          name: hello
        spec:
          restartPolicy: Never
          containers:
            - image: busybox
              name: hello
              args: [ "/bin/sh", "-c", "date" ]
              resources:
                requests:
                  cpu: "200m"
                  memory: "1Gi"
                limits:
                  cpu: "200m"
                  memory: "1Gi"
