apiVersion: v1
kind: Pod
metadata:
  name: pod11
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: data
      emptyDir: { }
  initContainers:
    - name: init
      image: busybox
      command: [ "/bin/sh", "-c", "echo 'some data' >> /data/file.txt" ]
      volumeMounts:
        - name: data
          mountPath: /data
  containers:
    - name: main
      image: busybox
      command: [ "/bin/sh", "-c", "cat /data/file.txt" ]
      volumeMounts:
        - name: data
          mountPath: /data
