apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-configmap
  name: nginx-configmap
spec:
  volumes:
    - name: configmap
      configMap:
        name: another-config
  containers:
    - image: nginx
      name: nginx-configmap
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "200m"
          memory: "1Gi"
        requests:
          cpu: "200m"
          memory: "1Gi"
      volumeMounts:
        - name: configmap
          mountPath: /also/a/path
  dnsPolicy: ClusterFirst
  restartPolicy: Never
