apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    type: frontEnd
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      type: frontEnd
  strategy: { }
  template:
    metadata:
      labels:
        app: nginx
        type: frontEnd
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"