apiVersion: v1
kind: Pod
metadata:
  labels:
    access-nginx: "true"
  name: nginx-allow-client
spec:
  containers:
    - image: busybox
      name: nginx-client
      command: [ "/bin/sh", "-c", "sleep 100000" ]
  dnsPolicy: ClusterFirst
  restartPolicy: Never