apiVersion: v1
kind: Pod
metadata:
  name: nginx-do-not-allow-client
spec:
  containers:
    - image: busybox
      name: nginx-client
      command: [ "/bin/sh", "-c", "sleep 100000" ]
  dnsPolicy: ClusterFirst
  restartPolicy: Never