apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-via-env
spec:
  containers:
    - name: pod-secrets-via-env
      image: nginx
      env:
        - name: CONFIDENTIAL
          valueFrom:
            secretKeyRef:
              name: bobs-secret
              key: password
