apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-via-file
spec:
  volumes:
    - name: secrets
      secret:
        secretName: "bobs-secret"
  containers:
    - name: pod-secrets-via-file
      image: nginx
      volumeMounts:
        - name: secrets
          mountPath: /secret
          readOnly: true
