apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      tolerations:
        - effect: NoExecute
          operator: Exists
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
