apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "200m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"

  dnsPolicy: ClusterFirst
  restartPolicy: Never