apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod12
  name: pod12
spec:
  nodeSelector:
    zone: dmz
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
    - image: busybox
      name: pod12
