apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: '*/1 * * * *'
  startingDeadlineSeconds: 22
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      name: hello
    spec:
      activeDeadlineSeconds: 10
      template:
        metadata:
          name: hello
        spec:
          restartPolicy: Never
          containers:
            - image: busybox
              name: hello
              command:
                - /bin/sh
                - -c
                - date