apiVersion: v1
kind: ConfigMap
metadata:
  name: another-config
data:
  index.html: "hello from config map!!!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: config-map-volume
          configMap:
            name: another-config
      containers:
        - image: nginx
          name: nginx-configmap
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: config-map-volume
              mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
