apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: frontEnd
  annotations:
    questionNo: four
spec:
  replicas: 4
  selector:
    matchLabels:
      type: frontEnd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx-pod
      labels:
        type: frontEnd
      annotations:
        questionNo: four
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: frontEnd
  annotations:
    questionNo: four
spec:
  type: ClusterIP
  selector:
    type: frontEnd
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80