apiVersion: v1
kind: Secret
metadata:
  name: another-secret
data:
  key1: dmFsdWU0
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: data
      emptyDir: { }
  initContainers:
    - name: int-container
      image: busybox
      env:
        - name: COOL_VARIABLE
          valueFrom:
            secretKeyRef:
              name: another-secret
              key: key1
      volumeMounts:
        - name: data
          mountPath: /data
      command:
        - /bin/sh
        - -c
        - echo $COOL_VARIABLE > /data/data.txt
  containers:
    - image: nginx
      name: nginx
      env:
        - name: COOL_VARIABLE
          valueFrom:
            secretKeyRef:
              name: another-secret
              key: key1
      volumeMounts:
        - name: data
          mountPath: /data
      command:
        - /bin/sh
        - -c
        - cat /data/data.txt