apiVersion: v1
kind: Secret
metadata:
  name: another-secret
data:
  key1: dmFsdWU0
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  annotations:
    secretName: another-secret
  labels:
    run: nginx-secret
spec:
  nodeSelector:
    name: "minion2"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
    - image: nginx
      name: nginx-secret
      env:
        - name: COOL_VARIABLE
          valueFrom:
            secretKeyRef:
              name: another-secret
              key: key1
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
