# Storage Class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-disk
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
---
# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  storageClassName: local-disk
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /tmp/pv
---
# PVC 2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: local-disk
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Mi
