apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deployment
      run: my-pod
  template:
    metadata:
      labels:
        app: my-deployment
        run: my-pod
    spec:
      containers:
        - image: nginx
          name: my-pod